export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";

export const USER_SIGNUP_SUCCESS="USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR="USER_SIGNUP_ERROR";
export const USER_SIGNUP_REQUEST="USER_SIGNUP_REQUEST";