export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

// export const SSO_LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const SSO_LOGIN_ERROR = "LOGIN_ERROR";
// export const SSO_LOGIN_REQUEST = "LOGIN_REQUEST";